### ISSUE TITLE
Tried but seems like something not done correctly by me

### ISSUE THREAD

**Issue by cs59** [asdfugil/haxx#2]
I tried this on checkra1n device 8plus 14.8 and I tried and rebooted my device after doing all steps also fixing provider..... file, but after reboot there's no changes am seeing, also do we have to cd in haxx-master folder and have to run 'make' command? becoz I tried and got unsupported architecture and 20 many more errors, I just direct copied haxx.c and provider_internal.c file so is this wrong thing I done?

**Comment by asdfugil** [comment]
there are changes, /private/var/haxx/haxx.log is created.

**Comment by cs59** [comment]
> there are changes, /private/var/haxx/haxx.log is created.

Means I have done this right? Also there’s no log i see in /private/var/haxx/ no files
