### ISSUE TITLE
Cannot get code exec to work

### ISSUE THREAD

**Issue by alfiecg24** [asdfugil/haxx#7]
I have tried to test out this project, and I have followed the guide through every step, but upon rebooting I still cannot see the log in /private/var/haxx. Are there any known issues I should be aware of which would affect this?

**Comment by asdfugil** [comment]
it’s recommend that you create an empty file at /private/var/haxx.log first

**Comment by alfiecg24** [comment]
I tried it with the log created before a reboot, which helped. If I execute `fileproviderctl_internal` manually, there is output to the log file - but running `/usr/bin/fileprovderctl` does not produce any log and there is also no log output upon reboot.

**Comment by alfiecg24** [comment]
Closing this issue because I upgraded to iOS 15.6
